# Build do Backend
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /backend
COPY Teste-api-backend/pom.xml .
COPY Teste-api-backend/src ./src
RUN mvn clean package -DskipTests

# Runtime
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /backend/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]